#!/bin/sh

CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")

echo "[$CURRENT_TIME] Start logrotate....."

/usr/sbin/logrotate -f /etc/logrotate.conf
EXITVALUE=$?

if [ $EXITVALUE != 0 ]; then
    echo "[$CURRENT_TIME] ALERT: logrotate exited abnormally with [$EXITVALUE]"
else
    echo "[$CURRENT_TIME] logrotate completed successfully"
fi

echo "[$CURRENT_TIME] End logrotate....."

exit $EXITVALUE