# 机器人配置
mode: debug
port: 8073
timeout: 5

#redis配置
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0

# sdk 配置
sdk:
  collect: http://127.0.0.1:8073/api/v1/collect
  callback: http://127.0.0.1:8073/api/v1/callback
  gog7a6v8g: http://127.0.0.1:8075
  gog7a6v90: http://127.0.0.1:8076
  timeout: 30
  token: "9ec822b31bd4492a9b311bb1ba854f37"
  appId: ""
  uuid: ""
  license: "./config/ESdNvBGvhWQzXW9mWdPnRzMwtUtWNtjZNzZyVbik6wc919"