package constant

const SnsText = `
<TimelineObject>
    <id></id>
    <username></username>
    <createTime></createTime>
    <contentDesc><![CDATA[{{.Content}}]]></contentDesc>
    <contentDescShowType>0</contentDescShowType>
    <contentDescScene>3</contentDescScene>
    <private>0</private>
    <sightFolded>0</sightFolded>
    <showFlag>0</showFlag>
    <appInfo>
        <id></id>
        <version></version>
        <appName></appName>
        <installUrl></installUrl>
        <fromUrl></fromUrl>
        <isForceUpdate>0</isForceUpdate>
        <isHidden>0</isHidden>
    </appInfo>
    <sourceUserName></sourceUserName>
    <sourceNickName></sourceNickName>
    <statisticsData></statisticsData>
    <statExtStr></statExtStr>
    <ContentObject>
        <contentStyle>2</contentStyle>
        <title></title>
        <description></description>
        <mediaList></mediaList>
        <contentUrl></contentUrl>
    </ContentObject>
    <actionInfo>
        <appMsg>
            <messageAction></messageAction>
        </appMsg>
    </actionInfo>
    <location poiClassifyId="" poiName="" poiAddress="" poiClassifyType="0" city=""></location>
    <publicUserName></publicUserName>
    <streamvideo>
        <streamvideourl></streamvideourl>
        <streamvideothumburl></streamvideothumburl>
        <streamvideoweburl></streamvideoweburl>
    </streamvideo>
</TimelineObject>
`

const SnsImage = `
<TimelineObject>
    <id>0</id>
    <username></username>
    <createTime>1603345160</createTime>
    <contentDesc><![CDATA[{{.Content}}]]></contentDesc>
    <contentDescShowType>0</contentDescShowType>
    <contentDescScene>3</contentDescScene>
    <private>0</private>
    <sightFolded>0</sightFolded>
    <showFlag>0</showFlag>
    <contentattr><![CDATA[0]]></contentattr>
    <sourceUserName></sourceUserName>
    <sourceNickName></sourceNickName>
    <statisticsData></statisticsData>
    <weappInfo>
        <appUserName></appUserName>
        <pagePath></pagePath>
        <version><![CDATA[0]]></version>
        <isHidden>0</isHidden>
        <debugMode><![CDATA[0]]></debugMode>
        <shareActionId></shareActionId>
        <isGame><![CDATA[0]]></isGame>
        <messageExtraData></messageExtraData>
        <subType><![CDATA[0]]></subType>
        <preloadResources></preloadResources>
    </weappInfo>
    <ContentObject>
        <contentStyle><![CDATA[1]]></contentStyle>
        <contentSubStyle><![CDATA[0]]></contentSubStyle>
        <title></title>
        <description></description>
        <contentUrl></contentUrl>
        <mediaList>
            {{range .ImgInfos}}
            <media>
                <id>0</id>
                <type>2</type>
                <title></title>
                <private>0</private>
                <userData></userData>
                <subType>0</subType>
                <videoSize width="500" height="889"/>
                <url type="1" {{if .FileMd5}} md5="{{.FileMd5}}"{{end}}><![CDATA[{{.FileUrl}}]]></url>
                <thumb type="1"><![CDATA[{{.ThumbUrl}}]]></thumb>
            </media>
            {{end}}
        </mediaList>
    </ContentObject>
    <actionInfo>
        <appMsg>
            <mediaTagName></mediaTagName>
            <messageExt></messageExt>
            <messageAction></messageAction>
        </appMsg>
    </actionInfo>
    <appInfo>
        <id></id>
    </appInfo>
    <publicUserName></publicUserName>
    <streamvideo>
        <streamvideourl></streamvideourl>
        <streamvideothumburl></streamvideothumburl>
        <streamvideoweburl></streamvideoweburl>
    </streamvideo>
</TimelineObject>
`

const SnsUrl = `
<TimelineObject>
    <id>0</id>
    <username><![CDATA[]]></username>
    <createTime>1604548459</createTime>
    <contentDesc><![CDATA[{{.Content}}]]></contentDesc>
    <contentDescShowType>0</contentDescShowType>
    <contentDescScene>4</contentDescScene>
    <private>0</private>
    <sightFolded>0</sightFolded>
    <showFlag>0</showFlag>
    <appInfo>
        <id></id>
        <version></version>
        <appName></appName>
        <installUrl></installUrl>
        <fromUrl></fromUrl>
        <isForceUpdate>0</isForceUpdate>
    </appInfo>
    <sourceUserName></sourceUserName>
    <sourceNickName></sourceNickName>
    <statisticsData></statisticsData>
    <statExtStr></statExtStr>
    <ContentObject>
        <contentStyle>3</contentStyle>
        <title><![CDATA[{{.Title}}]]></title>
        <description><![CDATA[{{.Description}}]]></description>
        <contentUrl><![CDATA[{{.ContentUrl}}]]></contentUrl>
        <mediaList>
            <media>
                <id>0</id>
                <type>2</type>
                <title></title>
                <description></description>
                <private>0</private>
                <userData></userData>
                <subType>0</subType>
                <videoSize width="0" height="0"></videoSize>
                <url type="0" md5="" videomd5=""><![CDATA[{{.ThumbUrl}}]]></url>
                <lowBandUrl type="0"><![CDATA[{{.ThumbUrl}}]]></lowBandUrl>
                <thumb type="1"><![CDATA[{{.ThumbUrl}}]]></thumb>
            </media>
        </mediaList>
        <mmreadershare>
            <itemshowtype>0</itemshowtype>
            <nativepage>0</nativepage>
            <digest>
                <![CDATA[]]>
            </digest>
            <cover>
                <![CDATA[]]>
            </cover>
            <pubtime>0</pubtime>
            <duration>0</duration>
            <width>0</width>
            <height>0</height>
            <vid></vid>
            <funcflag>0</funcflag>
        </mmreadershare>
    </ContentObject>
    <actionInfo>
        <appMsg>
            <messageAction></messageAction>
        </appMsg>
    </actionInfo>
    <location poiClassifyId="" poiName="" poiAddress="" poiClassifyType="0" city=""></location>
    <publicUserName></publicUserName>
    <streamvideo>
        <streamvideourl></streamvideourl>
        <streamvideothumburl></streamvideothumburl>
        <streamvideoweburl></streamvideoweburl>
    </streamvideo>
</TimelineObject>
`

const SnsVideo = `
<TimelineObject>
    <id>0</id>
    <username><![CDATA[]]></username>
    <createTime>1603346167</createTime>
    <contentDesc><![CDATA[{{.Content}}]]></contentDesc>
    <contentDescShowType>0</contentDescShowType>
    <contentDescScene>0</contentDescScene>
    <private>0</private>
    <sightFolded>0</sightFolded>
    <showFlag>0</showFlag>
    <appInfo>
        <id></id>
        <version></version>
        <appName></appName>
        <installUrl></installUrl>
        <fromUrl></fromUrl>
        <isForceUpdate>0</isForceUpdate>
    </appInfo>
    <sourceUserName></sourceUserName>
    <sourceNickName></sourceNickName>
    <statisticsData></statisticsData>
    <statExtStr></statExtStr>
    <ContentObject>
        <contentStyle>15</contentStyle>
        <title></title>
        <description>Sight</description>
        <mediaList>
            <media>
                <id>0</id>
                <type>6</type>
                <title></title>
                <description><![CDATA[{{.Content}}]]></description>
                <private>0</private>
                <userData></userData>
                <subType>0</subType>
                <videoSize width="720" height="1280"/>
                <url type="1">
                    <![CDATA[{{.Video.FileUrl}}]]>
                </url>
                <thumb type="1"><![CDATA[{{.Video.ThumbUrl}}]]></thumb>
                <size width="720" height="1280" totalSize="1649264"/>
                <videoDuration>
                    {{if .Video.VideoDuration}}
                        <![CDATA[{{.Video.VideoDuration}}]]>
                    {{end}}
                </videoDuration>
            </media>
        </mediaList>
    </ContentObject>
</TimelineObject>
`

const SendApplet = `
<appmsg appid="" sdkver="0">
    <title>{{.Title}}</title>
    <des>{{.Title}}</des>
    <type>33</type>
    <url>https://mp.weixin.qq.com/mp/waerrpage?appid={{.AppId}}&amp;type=upgrade&amp;upgradetype=3#wechat_redirect</url>
    <appattach>
        <cdnthumburl>
            3057020100044b304902010002048399cc8402032f58510204922a83b7020463d9b375042465613136623764312d396633652d343638352d626465332d6336643962343961643561320204011400030201000405004c54a100
        </cdnthumburl>
        <cdnthumbmd5>fc5bc8694248295ef09e9fbea18596e1</cdnthumbmd5>
        <cdnthumblength>49758</cdnthumblength>
        <cdnthumbwidth>720</cdnthumbwidth>
        <cdnthumbheight>576</cdnthumbheight>
        <cdnthumbaeskey>d48853fcee2638a34fd6b91c048c47ff</cdnthumbaeskey>
        <aeskey>d48853fcee2638a34fd6b91c048c47ff</aeskey>
        <encryver>0</encryver>
        <filekey>wxid_6qzt22_452_1675211637</filekey>
    </appattach>
    <sourceusername>{{.UserName}}</sourceusername>
    <sourcedisplayname>{{.DisplayName}}</sourcedisplayname>
    <md5>fc5bc8694248295ef09e9fbea18596e1</md5>
    <recorditem><![CDATA[(null)]]></recorditem>
    <uploadpercent>98</uploadpercent>
    <weappinfo>
        <username><![CDATA[{{.UserName}}]]></username>
        <appid><![CDATA[{{.AppId}}]]></appid>
        <type>2</type>
        <version>13</version>
        <weappiconurl></weappiconurl>
        <pagepath><![CDATA[{{.PagePath}}]]></pagepath>
        <shareId><![CDATA[0_wxb4e9537053626aae_704fc54cfed53ed6c8e85a2cf504a0f5_1675211636_0]]></shareId>
        <appservicetype>0</appservicetype>
        <brandofficialflag>0</brandofficialflag>
        <showRelievedBuyFlag>0</showRelievedBuyFlag>
        <subType>0</subType>
        <isprivatemessage>0</isprivatemessage>
    </weappinfo>
</appmsg>
`
