package khan

const (
	loginQrCode      = "/wxsdk/lgoin/getloginqrcode"
	checkLoginQrCode = "/wxsdk/lgoin/checkloginqrcode"
	longOpen         = "/wxsdk/longv2/open"
	secAutoAuth      = "/wxsdk/lgoin/secautoauth"
	createApp        = "/wxsdk/lgoin/createapp"
	heartbeat        = "/wxsdk/lgoin/heartbeat"
	logout           = "/wxsdk/lgoin/logout"

	postText     = "/wxsdk/message/sendmsg"
	postImage    = "/wxsdk/message/sendimg"
	sendFile     = "/wxsdk/message/sendfile"
	sendLink     = "/wxsdk/message/sendlink"
	sendVoice    = "/wxsdk/message/sendvoice"
	sendVideo    = "/wxsdk/message/sendvideo"
	sendNameCard = "/wxsdk/message/sendmsg"
	sendEmoji    = "/wxsdk/message/sendemoji"
	sendApplet   = "/wxsdk/message/sendapplet"
	downloadImg  = "/wxsdk/other/resourcedownload"

	contactList         = "/wxsdk/contacts/listings"
	contactSearch       = "/wxsdk/contacts/search"
	contactAdd          = "/wxsdk/contacts/verifyuser"
	contactDel          = "/wxsdk/contacts/delete"
	contactInfo         = "/wxsdk/contacts/batchgetbriefinfo"
	contactDetail       = "/wxsdk/contacts/detail"
	contactSetOnlyChat  = "/wxsdk/other/multifunctional"
	contactSetRemark    = "/wxsdk/contacts/setremark"
	contactUploadMobile = "/wxsdk/contacts/uploadmcontact"
	contactGetMobile    = "/wxsdk/contacts/getmfriend"

	personalProfile         = "/wxsdk/personal/getprofile"
	personalQrcode          = "/wxsdk/personal/getqrcode"
	personalSafety          = "/wxsdk/personal/getsafetyinfo"
	personalPrivacySetting  = "wxsdk/personal/privacysettings"
	personalUploadHdHeadImg = "/wxsdk/personal/uploadhdheadimg"

	labelAdd    = "/wxsdk/label/add"
	labelDelete = "/wxsdk/label/delete"
	labelList   = "/wxsdk/label/list"
	labelModify = "/wxsdk/label/modifylist"

	chatroomCreate           = "/wxsdk/group/create"
	chatroomMember           = "/wxsdk/group/member"
	chatroomDetail           = "/wxsdk/group/detail"
	chatroomAnnouncement     = "/wxsdk/group/infodetail"
	chatroomSetAnnouncement  = "/wxsdk/group/setannouncement"
	chatroomModifyName       = "/wxsdk/group/setname"
	chatroomModifyRemark     = "/wxsdk/group/setremark"
	chatroomModifyMyNickName = "/wxsdk/group/setmynickname"
	chatroomTopPing          = "/wxsdk/group/topping"
	chatroomContactSaveList  = "/wxsdk/group/movecontractlist"
	chatroomSetSilence       = "/wxsdk/group/setdisturb"

	snsUploadImg = "/wxsdk/sns/uploadimage"

	favorSync   = "/wxsdk/favor/sync"
	favorDetail = "/wxsdk/favor/getcontent"
	favorDelete = "/wxsdk/favor/delete"
)
