package khan

const (
	loginQrCode      = "/wxsdk/lgoin/getloginqrcode"
	checkLoginQrCode = "/wxsdk/lgoin/checkloginqrcode"
	longOpen         = "/wxsdk/longv2/open"
	secAutoAuth      = "/wxsdk/lgoin/secautoauth"
	createApp        = "/wxsdk/lgoin/createapp"
	heartbeat        = "/wxsdk/lgoin/heartbeat"
	logout           = "/wxsdk/lgoin/logout"

	postText     = "/wxsdk/message/sendmsg"
	postImage    = "/wxsdk/message/sendimg"
	sendFile     = "/wxsdk/message/sendfile"
	sendLink     = "/wxsdk/message/sendlink"
	sendVoice    = "/wxsdk/message/sendvoice"
	sendVideo    = "/wxsdk/message/sendvideo"
	sendNameCard = "/wxsdk/message/sendmsg"
	sendEmoji    = "/wxsdk/message/sendemoji"
	sendApplet   = "/wxsdk/message/sendapplet"
	downloadImg  = "/wxsdk/other/resourcedownload"
	revokeMsg    = "/wxsdk/message/revoke"
	forwardUrl   = "/wxsdk/message/sendapp"
	forwardVideo = "/wxsdk/message/sendcdnvideo"
	forwardImage = "/wxsdk/message/sendcdnimg"
	forwardFile  = "/wxsdk/message/sendcdnfile"

	contactList         = "/wxsdk/contacts/listings"
	contactSearch       = "/wxsdk/contacts/search"
	contactAdd          = "/wxsdk/contacts/verifyuser"
	contactDel          = "/wxsdk/contacts/delete"
	contactInfo         = "/wxsdk/contacts/batchgetbriefinfo"
	contactDetail       = "/wxsdk/contacts/detail"
	contactSetOnlyChat  = "/wxsdk/other/multifunctional"
	contactSetRemark    = "/wxsdk/contacts/setremark"
	contactUploadMobile = "/wxsdk/contacts/uploadmcontact"
	contactGetMobile    = "/wxsdk/contacts/getmfriend"

	personalProfile         = "/wxsdk/personal/getprofile"
	personalQrcode          = "/wxsdk/personal/getqrcode"
	personalSafety          = "/wxsdk/personal/getsafetyinfo"
	personalPrivacySetting  = "wxsdk/personal/privacysettings"
	personalUploadHdHeadImg = "/wxsdk/personal/uploadhdheadimg"

	labelAdd    = "/wxsdk/label/add"
	labelDelete = "/wxsdk/label/delete"
	labelList   = "/wxsdk/label/list"
	labelModify = "/wxsdk/label/modifylist"

	chatroomCreate           = "/wxsdk/group/create"
	chatroomMember           = "/wxsdk/group/member"
	chatroomDetail           = "/wxsdk/group/detail"
	chatroomAnnouncement     = "/wxsdk/group/infodetail"
	chatroomSetAnnouncement  = "/wxsdk/group/setannouncement"
	chatroomModifyName       = "/wxsdk/group/setname"
	chatroomModifyRemark     = "/wxsdk/group/setremark"
	chatroomModifyMyNickName = "/wxsdk/group/setmynickname"
	chatroomTopPing          = "/wxsdk/group/topping"
	chatroomContactSaveList  = "/wxsdk/group/movecontractlist"
	chatroomSetSilence       = "/wxsdk/group/setdisturb"
	chatroomQrcode           = "/wxsdk/group/getqrcode"

	snsUploadImg                 = "/wxsdk/sns/uploadimage"
	snsFriendPage                = "/wxsdk/sns/userpage"
	snsMyselfPage                = "/wxsdk/sns/timeline"
	snsDetail                    = "/wxsdk/sns/queryiddetail"
	snsLike                      = "/wxsdk/sns/comment"
	snsComment                   = "/wxsdk/sns/comment"
	snsCancelLike                = "/wxsdk/sns/funcop"
	snsDeleteComment             = "/wxsdk/sns/funcop"
	snsSetPrivacy                = "/wxsdk/sns/funcop"
	snsDelete                    = "/wxsdk/sns/funcop"
	snsSetPrivacyScope           = "/wxsdk/sns/privacyset"
	snsStrangerVisibilityEnabled = "/wxsdk/sns/privacyset"
	snsUploadVideo               = "/wxsdk/sns/uploadvideo"
	snsSendText                  = "/wxsdk/sns/tweet"
	snsSendUrl                   = "/wxsdk/sns/tweet"
	snsSendExcludeImage          = "/wxsdk/sns/tweet"
	snsSendVideo                 = "/wxsdk/sns/tweet"
	snsSendImage                 = "/wxsdk/sns/tweetimg"

	favorSync   = "/wxsdk/favor/sync"
	favorDetail = "/wxsdk/favor/getcontent"
	favorDelete = "/wxsdk/favor/delete"

	redPacket    = "/wxsdk/tenpay/openhb"
	collectMoney = "/wxsdk/tenpay/collectmoney"

	batchHeartBeat = "/api/toolbox/batchheartbeat"
)
